### ISSUE TITLE
qieqie大侠，如何让rose接收xml或json请求呢？

### ISSUE THREAD

**Issue by zhegexiaohuozi** [paoding-code/paoding-rose#6]
qieqie大侠，如何让rose接收xml或json请求呢？而不只是通常的K-V

**Comment by bsqql123** [comment]
@zhegexiaohuozi rose原生确实不支持，我自己用拦截器实现了一个类似于Spring 的@RequestBody注解，可以接收application/json请求，代码地址：
https://github.com/bsqql123/paoding-rose-hello/blob/master/src/main/java/net/paoding/rose/samples/hellorose/controllers/IndexController.java


拦截器实现在这里：
https://github.com/bsqql123/paoding-rose-hello/blob/master/src/main/java/net/paoding/rose/samples/hellorose/controllers/AccessTrackInterceptor.java
